name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14  # Use macOS 14 for Xcode 16 support
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer
        
      - name: Check Xcode Version
        run: xcodebuild -version
        
      - name: Check Swift Version
        run: swift --version
        
      - name: Build SparkDI
        run: swift build
        
      - name: Run Swift Testing Tests
        run: swift test --enable-swift-testing
                
      - name: Generate Test Report
        if: always()
        run: |
          swift test --enable-swift-testing --parallel || true
          echo "Test execution completed"
