name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15  # Use macOS 15 for Xcode 16 support
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer
        
      - name: Show Xcode and Swift Version
        run: xcodebuild -version
             swift --version
        
      - name: Build SparkDI
        run: swift build --build-tests
                
      - name: Run Swift Testing Tests
        run: swift test --enable-code-coverage --parallel
